---
- name: Create node
  bigip_node:
    host: "{{ item.address }}"
    name: "{{ item.address }}"
    partition: "{{ partition }}"
    description: "{{ item.description | default(omit) }}"
    provider:
      server: "{{ _active_device_address }}"
      user: "{{ f5_cred.f5_user }}"
      password: "{{ f5_cred.f5_password }}"
      server_port: "{{ provider_server_port }}"
      no_f5_teem: true
      transport: rest
      validate_certs: "{{ provider_validate_certs }}"
  loop: "{{ node_list }}"
  register: _create_node_results
  ignore_errors: yes

- name: Display nodes that were already present
  debug:
    msg: "Node {{ item.item.address }} already present"
  when: not item.changed
  loop: "{{ _create_node_results.results }}"

- name: Add pool members
  bigip_pool_member:
    state: present
    pool: "{{ pool_name }}"
    partition: "{{ partition }}"
    host: "{{ item.address }}"
    name: "{{ item.address }}"
    port: "{{ pool_port }}"
    provider:
      server: "{{ _active_device_address }}"
      user: "{{ f5_cred.f5_user }}"
      password: "{{ f5_cred.f5_password }}"
      server_port: "{{ provider_server_port }}"
      no_f5_teem: true
      transport: rest
      validate_certs: "{{ provider_validate_certs }}"
  loop: "{{ node_list }}"
