---
- name: Add pool member
  bigip_pool_member:
    state: present
    pool: "{{ _pool_result.name }}"
    partition: "{{ partition }}"
    host: "{{ item.address }}"
    name: "{{ item.name }}"
    port: "{{ pool_port }}"
    provider:
      server: "{{ _active_device_address }}"
      user: "{{ f5_cred.f5_user }}"
      password: "{{ f5_cred.f5_password }}"
      server_port: "{{ provider_server_port }}"
      no_f5_teem: "{{ provider_omit_telemetry }}"
      transport: "{{ provider_transport }}"
      validate_certs: "{{ provider_validate_certs }}"
  loop: "{{ _successfully_created_nodes }}"
