---
- name: Validate node params
  assert:
    that:
      - item.name is defined
      - item.name is string
      - item.address is defined
      - item.address is string
  loop: "{{ nodes_to_create }}"

- name: Add node
  bigip_node:
    host: "{{ item.address }}"
    name: "{{ item.name }}"
    provider:
      server: "{{ _active_device_address }}"
      user: "{{ f5_cred.f5_user }}"
      password: "{{ f5_cred.f5_password }}"
      server_port: "{{ provider_server_port }}"
      no_f5_teem: "{{ provider_omit_telemetry }}"
      transport: "{{ provider_transport }}"
      validate_certs: "{{ provider_validate_certs }}"
  loop: "{{ nodes_to_create }}"
