---
- name: Validate node params
  assert:
    that:
      - node.name is defined
      - node.name is string
      - node.address is defined
      - node.address is string
  loop: "{{ nodes_to_create }}"
  loop_control:
    label: "{{ node }}"

- name: Add node
  bigip_node:
    host: "{{ node.address }}"
    name: "{{ node.name }}"
    provider:
      server: "{{ _active_device_address }}"
      user: "{{ f5_cred.f5_user }}"
      password: "{{ f5_cred.f5_password }}"
      server_port: "{{ provider_server_port }}"
      no_f5_teem: "{{ provider_omit_telemetry }}"
      transport: "{{ provider_transport }}"
      validate_certs: "{{ provider_validate_certs }}"
  loop: "{{ nodes_to_create }}"
  loop_control:
    label: "{{ node }}"
