---
- name: Display input hosts
  debug:
    msg: "{{ f5_cred.f5_hosts.split(',') }}"
  
- name: Validate f5 credential fields
  assert:
    that:
      - f5_cred.f5_user is defined
      - f5_cred.f5_password is defined
      - (f5_cred.f5_hosts | split(',') | length) == 2

- name: Check if pool_name and partition are provided
  assert:
    that:
      - pool_name is defined and pool_name | length > 0
      - partition is defined and partition | length > 0

- name: Validate pool operation
  assert:
    that:
      - pool_operation is defined 
      - pool_operation in ['create', 'update', 'remove']
    fail_msg: "pool_operation must be one of: create, update, or remove"
      
- name: Get active device
  ansible.builtin.include_tasks:
    file: get_active_device.yaml

- name: Create pool
  ansible.builtin.include_tasks:
    file: create_pool.yaml
  when: pool_operation == "create"

- name: Update pool
  ansible.builtin.include_tasks:
    file: update_pool.yaml
  when: pool_operation == "update" or pool_operation == "create"

- name: Remove pool
  ansible.builtin.include_tasks:
    file: remove_pool.yaml
  when: pool_operation == "remove"
