---
- name: Validate f5 credential fields
  assert:
    that:
      - (f5_cred.f5_user | length) > 0
      - (f5_cred.f5_password | length) > 0
      - (f5_cred.f5_hosts | split(',') | length) == 2

- name: Display first host
  debug:
    msg: "{{ f5_cred.f5_hosts.split(',') | first }}"

- name: Device info
  bigip_device_info:
    gather_subset:
      - devices
    provider:
      server: "{{ f5_cred.f5_hosts.split(',') | first }}"
      user: "{{ f5_cred.f5_user }}"
      password: "{{ f5_cred.f5_password }}"
      server_port: 443
      no_f5_teem: true
      transport: rest
      validate_certs: false
  register: result

- name: Show registered results
  debug:
    msg: "{{ result }}"
