---
- name: Display input hosts
  debug:
    msg: "{{ f5_cred.f5_hosts.split(',') }}"
  
- name: Validate f5 credential fields
  assert:
    that:
      - f5_cred.f5_user is defined
      - f5_cred.f5_password is defined
      - (f5_cred.f5_hosts | split(',') | length) == 2

- name: Get active device
  ansible.builtin.include_tasks:
    file: get_active_device.yaml

- name: Create nodes
  ansible.builtin.include_tasks:
    file: create_nodes.yaml
  when: "nodes_to_create is defined and nodes_to_create | list | length > 0"

- name: Create pool
  ansible.builtin.include_tasks:
    file: create_pool.yaml

- name: Add nodes to pool
  ansible.builtin.include_tasks:
    file: add_nodes_to_pool.yaml
  when: "_pool_result.name is defined and nodes_to_create is defined and nodes_to_create | list | length > 0"

- name: Create virtual server
  ansible.builtin.include_tasks:
    file: create_vs.yaml
