---
- name: Validate inputs and resolve credentials
  ansible.builtin.include_tasks:
    file: validations.yaml

- name: Get active device
  ansible.builtin.include_tasks:
    file: get_active_device.yaml

- name: Create pool
  ansible.builtin.include_tasks:
    file: create_pool.yaml
  when: pool_operation == "create"

- name: Update pool
  ansible.builtin.include_tasks:
    file: update_pool.yaml
  when: pool_operation == "update" or pool_operation == "create"

- name: Remove pool
  ansible.builtin.include_tasks:
    file: remove_pool.yaml
  when: pool_operation == "remove"
